version: '3'
services:
  zookeeper:
    restart: always
    env_file:
      - .env
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'

  kafka:
    restart: always
    env_file:
      - .env
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper




